version: "3.3"

services:
  nginx:
    container_name: 'nginx'
    image: 'nginx'
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - /tmp/acme_challenge:/tmp/acme_challenge:wr
      - /etc/letsencrypt/archive:/etc/letsencrypt/live
      - ./certbot/www:/var/www/certbot
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - app
    restart: always
    depends_on:
     - webserver

  webserver:
    container_name: 'webserver'
    image: 'webserver'
    build:
      context: .
      dockerfile: webserver/Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/webserver
    volumes:
      - ./webserver:/webserver
    networks:
      - app
    ports:
      - 3000:3000
    restart: always
    command: node webserver/server.js
    depends_on:
      - mongodb

  mongodb:
    container_name: 'mongodb'
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
    networks:
      - app

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # entrypoint: "certbot certonly --webroot --webroot-path /var/www/certbot/ -d backend.ruchimaniar.com -m 'reillymclaren20@gmail.com' --agree-tos"
    depends_on:
      - nginx
volumes:
  dbdata6:


networks:
  app:
    driver: bridge


